"""Reading and writing runs.

Datasets are stored as canonical JSON rather than a columnar format. At the
sizes reconciliation actually runs at this is not the bottleneck, and JSON
buys two things that matter more: a byte-for-byte stable encoding that can be
hashed, and a file a human can open when a number looks wrong.

Nothing here is committed to version control. A dataset is a pure function of
its seed and difficulty, so the repository stores the generator instead of
its output.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from pydantic import BaseModel

from milan.chaos.config import Difficulty, GenerationConfig
from milan.chaos.generator import ChaosEngine
from milan.domain.dataset import Dataset
from milan.domain.results import ReconReport

DATASET_FILE = "dataset.json"
CONFIG_FILE = "config.json"
REPORT_FILE = "report.json"
EVALUATION_FILE = "evaluation.json"


class StaleDatasetError(RuntimeError):
    """The dataset on disk is not what this code would generate today.

    Raised rather than warned about. A stored run is only useful because it
    is a pure function of its config, and once the generator has moved on
    that is no longer true: the file still loads, still looks well formed,
    and now describes a merchant this version of the engine never produced.

    This is not hypothetical. It happened during the day-6 pass - a run
    generated before the reference-twin defect was added kept scoring, and
    reported a baseline eight percentage points away from the published one
    with nothing on screen to suggest anything was wrong. Numbers from a
    stale dataset are not slightly off, they are about a different dataset.
    """


def default_root() -> Path:
    """`data/` beside the repository root, wherever the engine is installed."""
    return Path(__file__).resolve().parents[4] / "data"


def run_directory(root: Path, seed: int, difficulty: Difficulty | str) -> Path:
    name = difficulty.value if isinstance(difficulty, Difficulty) else difficulty
    return root / "runs" / f"{name}-seed{seed}"


def write(model: BaseModel, path: Path) -> Path:
    """Serialise one model to canonical JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(model.model_dump_json(indent=2), encoding="utf-8")
    return path


def save_dataset(dataset: Dataset, root: Path, config: GenerationConfig) -> Path:
    """Write a run, and the config that is the only reason it can be trusted.

    The config is a sidecar rather than a field on `Dataset` so that the
    dataset digest keeps meaning "this data". Folding the request into the
    hash would make two byte-identical datasets hash differently because one
    was asked for with a flag spelled another way.
    """
    directory = run_directory(root, dataset.seed, dataset.difficulty)
    write(config, directory / CONFIG_FILE)
    return write(dataset, directory / DATASET_FILE)


def load_dataset(
    root: Path, seed: int, difficulty: Difficulty | str, *, verify: bool = True
) -> Dataset:
    """Read a stored run, having first proved it is still current.

    `verify` regenerates from the recorded config and compares digests. It
    costs about twenty milliseconds at six hundred orders and it is the
    difference between a number and a number about known data, so it is on
    by default and there is no flag to turn it off from the command line.
    """
    directory = run_directory(root, seed, difficulty)
    path = directory / DATASET_FILE
    if not path.exists():
        raise FileNotFoundError(
            f"no dataset at {path}. Generate one first: "
            f"milan generate --seed {seed} --difficulty "
            f"{difficulty.value if isinstance(difficulty, Difficulty) else difficulty}"
        )
    dataset = Dataset.model_validate_json(path.read_text(encoding="utf-8"))
    if verify:
        check_current(dataset, directory)
    return dataset


def load_config(directory: Path) -> GenerationConfig | None:
    path = directory / CONFIG_FILE
    if not path.exists():
        return None
    return GenerationConfig.model_validate_json(path.read_text(encoding="utf-8"))


def check_current(dataset: Dataset, directory: Path) -> None:
    """Regenerate from the recorded config; raise if the result has moved.

    A missing config file is treated the same way. It means the run predates
    this check or was assembled by hand, and either way there is nothing to
    regenerate from - which is exactly the state where trusting the file is
    unjustified.
    """
    config = load_config(directory)
    if config is None:
        raise StaleDatasetError(
            f"{directory / DATASET_FILE} has no config beside it, so there is no way "
            f"to confirm this generator produced it. Regenerate it."
        )
    if content_hash(ChaosEngine(config).generate()) != content_hash(dataset):
        raise StaleDatasetError(
            f"{directory / DATASET_FILE} was generated by a different version of the "
            f"chaos engine, so any number scored against it describes data this code "
            f"no longer produces. Regenerate it: milan generate --seed {config.seed} "
            f"--difficulty {config.difficulty.value} --orders {config.order_count}"
            + (" --withholding" if config.rates.tds_applies else "")
        )


def save_report(report: ReconReport, root: Path) -> Path:
    directory = run_directory(root, report.seed, report.difficulty)
    return write(report, directory / REPORT_FILE)


def content_hash(model: BaseModel) -> str:
    """A stable digest of a model's canonical encoding.

    Used by `milan reproduce`, which regenerates a dataset and compares
    digests. That is what turns "reproducible" from a claim in a README into
    something the build can fail on.
    """
    payload = model.model_dump_json().encode("utf-8")
    return hashlib.sha256(payload).hexdigest()
